StadGent/laravel_site_opening-hours

- resources/assets/js/App.vue
- resources/assets/js/components/RowService.vue
- resources/assets/js/components/RowServiceAdmin.vue
- resources/assets/js/components/RowUser.vue
- resources/assets/js/components/RowUserService.vue
- resources/assets/js/components/RowUserServiceAdmin.vue
- resources/assets/js/mixins/RowService.js
- resources/assets/js/mixins/auth.js
- resources/assets/js/mixins/services.js
- resources/assets/js/page/PageChannel.vue
- resources/assets/js/page/PageHome.vue
- resources/assets/js/page/PageService.vue
- resources/assets/js/page/PageUser.vue
- resources/assets/sass/app.scss
> Update columns for list of user services

- app/Repositories/LodServicesRepository.php
- app/Services/SparqlService.php
- fetch services from a SPARQL endpoint
- create a job that fetches uses the fetched services in order to upsert them in the database
- create a separate SPARQL service that facilitates SPARQL querying
- schedule the job weekly
> Issue #27 

- resources/assets/js/components/RowService.vue
- resources/assets/js/components/RowServiceAdmin.vue
- resources/assets/js/mixins/RowService.js
- resources/assets/js/mixins/users.js
- resources/assets/js/page/PageHome.vue
> Add button to add user from service overview

- resources/assets/js/lib.js
- resources/assets/js/page/PageChannel.vue
> Add some color to active version

- resources/assets/js/mixins/RowService.js
> Update version status messages

- resources/assets/js/lib.js
- resources/assets/js/mixins/RowService.js
> Update alerts to be more comprehensive

- composer.lock
- gulpfile.js
- resources/assets/js/components/CalendarEditor.vue
- resources/assets/js/components/Pagination.vue
- resources/assets/js/components/RowService.vue
- resources/assets/js/components/RowServiceAdmin.vue
- resources/assets/js/components/RowServiceDraft.vue
- resources/assets/js/components/RowUser.vue
- resources/assets/js/mixins/services.js
- resources/assets/js/page/PageHome.vue
- resources/assets/sass/_variables.scss
- resources/assets/sass/app.scss
OPEN-32 & OPEN-43
Main issues: updated table layout & provided 'deactivate' button.
Also moved search field and buttons to improve ux and match other pages.
> OPEN-32, OPEN-43: Improve services GUI

- app/Http/Controllers/ServicesController.php
- resources/assets/js/bootstrap.js
- routes/api.php
- tests/controllers/ServicesControllerTest.php
refactor service controller in use of auth 
now able to connect to index by anonimous user and logged in user and get auth user by $request->user('api')
+ added tests for all request types
> OPEN-1 refactor service controller for auth checks

- app/Exceptions/Handler.php
- app/Formatters/Openinghours/JsonFormatter.php
- app/Http/Controllers/QueryController.php
- app/Http/Requests/GetQueryRequest.php
- app/Providers/AppServiceProvider.php
- app/Services/ICalService.php
- app/Services/OpeninghoursService.php
- database/seeds/EventsTableSeeder.php
- routes/api.php
- tests/controllers/QueryControllerTest.php
- tests/formatters/OpeninghoursFormatterTest.php
- tests/services/OpeninghoursServiceTest.php
https://app.swaggerhub.com/apis/Digipolis/Openinghours/1.0.0
> OPEN-68 api V2

- resources/assets/js/lib.js
- resources/assets/js/mixins/modal.js
- resources/assets/js/mixins/status.js
Enkel commit https://github.com/StadGent/laravel_site_opening-hours/commit/cf0afe331741974fdd0c65203c8e547279cf66ef
De rest is code style.
> OPEN-94: Improve error handling for overlapping calendars

- resources/assets/js/components/CalendarEditor.vue
- resources/assets/js/components/EventEditor.vue
- resources/assets/js/components/Pikaday.vue
- resources/assets/js/constants.js
- resources/assets/js/defaults.js
- resources/assets/js/lib.js
- resources/assets/js/mixins/RowService.js
- resources/assets/js/page/PageVersion.vue
- resources/assets/sass/app.scss
- tests/TestCase.php
- tests/controllers/UI/RolesControllerTest.php
- tests/controllers/UI/UsersControllerTest.php
Can have unexpected consquences. 
Total refactoring is needed!
> OPEN-130: Refactored pikaday date handling.

- resources/assets/js/components/CalendarEditor.vue
- resources/assets/js/components/EventEditor.vue
- resources/assets/js/defaults.js
- resources/assets/js/lib.js
- resources/assets/js/mixins/modal.js
- tests/controllers/UI/UsersControllerTest.php
Also changed default dates to current day and removed 'sameLabel' validation which prohibited changing event frequencies.
> Feature/open 113: disabled 'save' in case of no events

- resources/assets/js/components/CalendarEditor.vue
**ERROR: fetchRecreatex did not pass the unit tests.**
> OPEN-165: Limited refactoring of dateTime handling for presets.

- app/Models/Ical.php
- resources/assets/js/components/CalendarEditor.vue
- resources/assets/js/components/EventEditor.vue
- resources/assets/js/modal/ModalText.vue
Inlcudes open-204 and open-119
> Feature/open 208 Enabled default openinghours past midnight.

- .env.example
- README.md
- resources/assets/js/components/RowService.vue
- resources/assets/js/components/RowServiceAdmin.vue
- resources/assets/js/components/RowServiceDraft.vue
- resources/assets/js/mixins/RowService.js
- resources/assets/js/page/PageHome.vue
- resources/assets/sass/app.scss
- resources/views/main.blade.php
- routes/api.php
in .env: VESTA_SOURE_URL nog toevoegen
PROD: 
http://mscrm.gentgrp.gent.be/VESTA/main.aspx?etc=1&extraqs=formid%3db053a39a-041a-4356-acef-ddf00182762b&id=%7b${identifier}%7d&pagetype=entityrecord
Start timer
QA:
http://mscrmqa.gentgrp.gent.be/VESTAACC/main.aspx?etc=1&extraqs=formid%3db053a39a-041a-4356-acef-ddf00182762b&id=%7b${identifier}%7d&pagetype=entityrecord
DEV/TEST:
http://mscrmqa.gentgrp.gent.be/VESTADEV/main.aspx?etc=1&extraqs=formid%3d22672043-c952-43c6-b6f8-bdba44b16e7a&id=%7b${identifier}%7d&pagetype=entityrecord
> Feature/open 217 Added vesta service source link.

- app/Services/ServiceService.php
**Unit tests not run!**
No tests updated or created.
> OPEN-219: Added updateVestaOpeninghours if service is pulled from draft.

- resources/assets/js/components/RowService.vue
- resources/assets/js/components/RowServiceAdmin.vue
- resources/assets/js/components/RowServiceDebug.vue
- resources/assets/js/mixins/RowService.js
- resources/assets/js/mixins/services.js
- resources/assets/js/page/PageHome.vue
Todo on test: check performance impact with large dataset.
> OPEN-239: Sort services by status.

- app/Repositories/ServicesRepository.php
- resources/assets/js/components/RowService.vue
- resources/assets/js/components/RowServiceAdmin.vue
- resources/assets/js/mixins/services.js
- resources/assets/js/page/PageHome.vue
- resources/assets/js/page/PageService.vue
* extended backend query for initial services fetch
* updated local services on each relevant update
> OPEN-259: Added 'expires on' in services overview and channels overview

- package.json
- resources/assets/js/components/EventEditor.vue
Replaced v-model by value and input.
> Fixed multi-day-select.

- .env.example
- app/Services/VestaService.php
Move from username/password combo to API key in the SOAP Header.
> Update vesta integration

- app/Jobs/FetchServices.php
- app/Repositories/LodServicesRepository.php
So we can add opening hours to the CRM POIs.
> Add crm to the services
